safe:        false
auto:        false
server:      false
server_port: 5000
baseurl:    /

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    false
markdown:    redcarpet
redcarpet:
  extensions: [:hard_wrap]

permalink:   /:categories/:title/
